/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/tetris`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/api/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/api/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/api/auth/me`; params?: Router.UnknownInputParams; } | { pathname: `/api/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/api/games/saveGame`; params?: Router.UnknownInputParams; } | { pathname: `/api/profil/profil`; params?: Router.UnknownInputParams; } | { pathname: `/api/profil/stats`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/stats`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/achievements`; params?: Router.UnknownOutputParams; } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/tetris`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/api/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/api/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/api/auth/me`; params?: Router.UnknownOutputParams; } | { pathname: `/api/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/api/games/saveGame`; params?: Router.UnknownOutputParams; } | { pathname: `/api/profil/profil`; params?: Router.UnknownOutputParams; } | { pathname: `/api/profil/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/leaderboard/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/achievements${`?${string}` | `#${string}` | ''}` | `/config${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/tetris${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/api/leaderboard${`?${string}` | `#${string}` | ''}` | `/api/auth/login${`?${string}` | `#${string}` | ''}` | `/api/auth/me${`?${string}` | `#${string}` | ''}` | `/api/auth/register${`?${string}` | `#${string}` | ''}` | `/api/games/saveGame${`?${string}` | `#${string}` | ''}` | `/api/profil/profil${`?${string}` | `#${string}` | ''}` | `/api/profil/stats${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/leaderboard/leaderboard${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/profile/stats${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/tetris`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/api/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/api/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/api/auth/me`; params?: Router.UnknownInputParams; } | { pathname: `/api/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/api/games/saveGame`; params?: Router.UnknownInputParams; } | { pathname: `/api/profil/profil`; params?: Router.UnknownInputParams; } | { pathname: `/api/profil/stats`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/stats`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
